debug

diff --git a/.github/workflows/main_matrix.yml b/.github/workflows/main_matrix.yml
--- a/.github/workflows/main_matrix.yml
+++ b/.github/workflows/main_matrix.yml
@@ -1,12 +1,10 @@
 name: Dummy Apple OTP Build Pipeline
-
 on:
   push:
     branches:
       - dummy-ci
   pull_request:
   workflow_dispatch:
-
 jobs:
   load-matrix:
     runs-on: ubuntu-latest
@@ -21,44 +19,41 @@ jobs:
           MATRIX=$(jq -c . .github/workflows/matrix_config.json)
           echo $MATRIX
           echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
-
       - name: Read Matrix from JSON
         id: read-matrix-debug
         run: |
-            if [ ! -f .github/workflows/matrix_config.json ]; then
-                echo "Error: matrix_config.json not found!" >&2
-                exit 1
-            fi
-            MATRIX=$(jq -c . .github/workflows/matrix_config.json)
-            if [ -z "$MATRIX" ]; then
-                echo "Error: matrix_config.json is empty or could not be read!" >&2
-                exit 1
-            fi
-            if ! echo "$MATRIX" | jq -e . > /dev/null; then
-                echo "Error: matrix_config.json contains invalid JSON!" >&2
-                exit 1
-            fi
-            echo $MATRIX
-            # echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
+          if [ ! -f .github/workflows/matrix_config.json ]; then
+              echo "Error: matrix_config.json not found!" >&2
+              exit 1
+          fi
+          MATRIX=$(jq -c . .github/workflows/matrix_config.json)
+          if [ -z "$MATRIX" ]; then
+              echo "Error: matrix_config.json is empty or could not be read!" >&2
+              exit 1
+          fi
+          if ! echo "$MATRIX" | jq -e . > /dev/null; then
+              echo "Error: matrix_config.json contains invalid JSON!" >&2
+              exit 1
+          fi
+          echo $MATRIX
+          # echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
+  build_openssl:
+    needs: load-matrix
+    uses: ./.github/workflows/build_openssl.yml
+    with:
+      matrix: ${{ needs.load-matrix.outputs.matrix }}
 
-#   build_openssl:
-#     needs: load-matrix
-#     uses: ./.github/workflows/build_openssl.yml
-#     with:
-#       matrix: ${{ needs.load-matrix.outputs.matrix }}
-
-#   build_otp_round_1:
-#     needs: [load-matrix, build_openssl]
-#     uses: ./.github/workflows/build_otp.yml
-#     with:
-#       matrix: ${{ needs.load-matrix.outputs.matrix }}
-#       round: 1
-
+  build_otp_round_1:
+    needs: [load-matrix, build_openssl]
+    uses: ./.github/workflows/build_otp.yml
+    with:
+      matrix: ${{ needs.load-matrix.outputs.matrix }}
+      round: 1
 #   build_nifs:
 #     needs: [load-matrix, build_otp_round_1]
 #     strategy:
 #       fail-fast: false
-#       matrix: ${{ fromJson(needs.load-matrix.outputs.matrix) }} 
+#       matrix: ${{ fromJson(needs.load-matrix.outputs.matrix) }}
 #     runs-on: macos-latest # Now here
 #     steps:
 #       - name: Call nifs workflow
